name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  call-workflow:
    uses: ./.github/workflows/status_embed.yml
    
    with:
      pr_author: ${{ github.event.pull_request.user.login }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_source: ${{ github.event.pull_request.head.label }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}