name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  github_event_path:
    runs-on: ubuntu-latest
    steps:
      - name: Store Pr json values
        run: pull_request_json=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request')
      - name: Echo values of pr json
        run: echo $pull_request_json

  #call-workflow:
    #uses: ./.github/workflows/reusable.yml
    #permissions:
      #contents: read
      #pull-requests: write
    
    #with:
      #pull-request-json: $pull_request_json
