name: Caller workflow

on:
  pull_request:
    branches: [main]

jobs:
  call-workflow:
    name: Invoke reusable
    uses: ./.github/workflows/reusable.yml
    permissions:
      contents: read
      pull-requests: write
    
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  echo-shit:
    name: Echo GH
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
