name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  github_event_path:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo $GITHUB_EVENT_PATH

  call-workflow:
    uses: ./.github/workflows/reusable.yml
    permissions:
      contents: read
      pull-requests: write
    
    with:
      config-path: .github/labeler.yml
      pull-request-json: $(cat $GITHUB_EVENT_PATH | jq -r '.pull_request')
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
