name: Caller workflow


env:
  GH_CONTEXT: ${{ toJson(github) }}

on:
  pull_request:
    branches: [main]

jobs:
  workflow_name:
    name: Echo GH workflow name
    runs-on: ubuntu-latest
    steps:
      - name: echow
        run: echo "$GH_CONTEXT"

  call-status-embed:
    name: Invoke status embed
    uses: ./.github/workflows/status_embed.yaml
    permissions:
      contents: read
      pull-requests: read
    

