name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  first:
    outputs:
      outcome: ${{ job.status }}
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - id: step2
        run: echo hello
      - id: step1
        run: exit -1    

  call-workflow:
    needs: first
    uses: ./.github/workflows/status_embed.yml
    with:
      job_status: ${{ needs.first.outputs.outcome }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
      