name: Caller workflow

on:
  pull_request:
    branches: [main]

jobs:
  workflow_name:
    name: Echo GH workflow name
    runs-on: ubuntu-latest
    steps:
      - name: echow
        run: echo ${{ toJson(github) }}

  call-status-embed:
    name: Invoke status embed
    uses: ./.github/workflows/status_embed.yaml
    permissions:
      contents: read
      pull-requests: read
    

