name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  github_event_path:
    runs-on: ubuntu-latest
    steps:
      - run: a=bbb && echo $a
      - name: Store PR related data in `myawesomevariable`
        run: myawesomevariable=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request')
      - name: Echo values of PR data
        run: |
          echo $myawesomevariable
          [ -z "$myawesomevariable" ] && exit 1

  #call-workflow:
    #uses: ./.github/workflows/reusable.yml
    #permissions:
      #contents: read
      #pull-requests: write
    
    #with:
      #pull-request-json: $pull_request_json
