name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  first:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo hello
      - id: step2
        run: exit -1

  call-workflow:

    uses: ./.github/workflows/status_embed.yml
    needs: first
    with:
      job_status: ${{ needs.first.result}}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
      