name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  first:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - id: step2
        run: echo ${{ toJSON(jobs) }}
      - id: step3
        run: echo ${{ steps.step2.conclusion }}
      - id: step1
        run: exit -1
    

  call-workflow:
    needs: first
    uses: ./.github/workflows/status_embed.yml
    with:
      job_status: ${{ needs.first.result }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
      