name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:
  first:
    outputs:
      outcome: ${{ job.status }}
    runs-on: ubuntu-latest
    steps:
      - id: step2
        run: echo hello
      - id: step1
        run: exit -1

  call-workflow:
    needs: first
    if: always()
    uses: shtlrs/.github/.github/workflows/status_embed.yaml@master
    with:
      job_status: ${{ needs.first.outputs.outcome }}
