name: Caller workflow

on:
  pull_request:
    branches: [main]

jobs:
  call-status-embed:
    name: Invoke status embed
    uses: ./.github/workflows/status_embed.yaml
    permissions:
      contents: read
      pull-requests: read
    

