name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  github_event_path:
    runs-on: ubuntu-latest
    steps:
      - name: Echo value of GITHUB_EVENT_PATH
        run: echo $GITHUB_EVENT_PATH
      - name: Echo PR data
        run: cat $GITHUB_EVENT_PATH | jq -r '.pull_request'
      - name: Dump pr data into a file
        run: cat $GITHUB_EVENT_PATH | jq -r '.pull_request' > test.json
      - name: list files
        run: ls
      - name: Read files
        run: cat test.json
      - name: Store PR related data in `pull_request_json`
        run: pull_request_json=$(cat $GITHUB_EVENT_PATH | jq -r '.pull_request')
      - name: Echo values of PR data
        run: |
          echo $pull_request_json
          [ -z "$pull_request_json" ] && exit 1

  #call-workflow:
    #uses: ./.github/workflows/reusable.yml
    #permissions:
      #contents: read
      #pull-requests: write
    
    #with:
      #pull-request-json: $pull_request_json
