name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  first:
    outputs:
      job_status: ${{ steps.step3.outputs.job_status }}
    runs-on: ubuntu-latest
    steps:
      - id: step2
        run: echo hello
      - id: step1
        run: exit -1
        continue-on-error: true
      - id: step3
        run: |
          if [[ ${{ success() }} ]]
          then
            echo job_status=success
          else
            echo job_status=failure
          fi
    

  call-workflow:
    needs: first
    uses: ./.github/workflows/status_embed.yml
    with:
      job_status: ${{ needs.first.outputs.job_status }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
      