name: Caller workflow

on:
  pull_request:
    branches: main

jobs:
  echo-shit:
  runs-on: ubuntu-latest
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  call-workflow:
    uses: ./.github/workflows/reusable.yml
    permissions:
      contents: read
      pull-requests: write
    
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

