name: Call a reusable workflow

on:
  pull_request:
    branches: [main]

jobs:

  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - run: exit 1
    continue-on-error: true

  call-workflow:
    uses: ./.github/workflows/status_embed.yml
    needs: first
    
    with:
      pr_author: ${{ github.event.pull_request.user.login }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_source: ${{ github.event.pull_request.head.label }}
      job_status: ${{ needs.first.result }}
    secrets:
      webhook_token: ${{ secrets.GHA_WEBHOOK_TOKEN }}
      