name: Reusable workfloww


on:
  workflow_call:
    inputs:
      pr_author:
        required: true
        type: string
      pr_title:
        required: true
        type: string
      pr_source:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      

jobs:
  read_heritage:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo ${{ inputs.pr_author }}
      - name: second
        run: echo ${{ inputs.pr_title }}