name: Reusable workflow


on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  echo-shit:
    - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
  obey-caller:
    runs-on: ubuntu-latest
    steps:
    - name: Echo inputs
      env:
          CFG_PATH: ${{ inputs.config-path }}
      run: echo "$CFG_PATH"