name: Reusable workfloww


on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo ${{ inputs.config-path }}
      - name: second
        run: echo ${{ pull_request_json }}